# ML Assignment 9

**A Bidirectional Associative Memory(BAM) is required to store the following  M = 4 pairs of patterns:**


**Set A:**  
- X1 = [1 1 1 1 1 1]
- X2 = [-1 -1 -1 -1 -1 -1]
- X3 = [1 -1 -1 1 1 1]
- X4 = [1 1 -1 -1 -1 -1]


**Set B:**
- Y1 = [1 1 1]
- Y2 = [-1 -1 -1]
- Y3 = [-1 1 1]
- Y4 = [1 -1 1]

**Using BAM algorithm, train a W matrix for BAM which can retrieve all the above mentioned 4 pairs.**

**Hence test the level of weight corrections of the BAM with examples.**

------

### Importing Required Headers

In [1]:
import numpy as np

### Initializing the Matrices

In [2]:
X = np.array([[1, 1, 1, 1, 1, 1],
              [-1, -1, -1, -1, -1, -1],
              [1, -1, -1, 1, 1, 1],
              [1, 1, -1, -1, -1, -1]])


Y = np.array([[1, 1, 1],
              [-1, -1, -1],
              [-1, 1, 1],
              [1, -1, 1]])

print("X shape = ", X.shape)
print("Y shape = ", Y.shape)

X shape =  (4, 6)
Y shape =  (4, 3)


### Calculating the W matrix

If You want to calculate it using a **for loop** : 

$
    W = \sum_{i=1}^{4} W_{i} \\
    where :  W_i = X_i^T * Y_i
$

If you want to use **vectorised implementation** : 

$
    W = X^T * Y
$

In [3]:
W = np.dot(X.T, Y)
print('W = \n', W)

W = 
 [[2 2 4]
 [4 0 2]
 [2 2 0]
 [0 4 2]
 [0 4 2]
 [0 4 2]]


### Activation function

There are 2 main types of activation functions : 

**Binary :**

$
bin(y_{in}) = \left\{
    \begin{array}\\
        1 , & \mbox{if } \ y_{in} > 0 \\
        0 , & \mbox{if } \ y_{in} < 0 \\
        y_{in} , & \mbox{if } \ y_{in} = 0
    \end{array}
\right.
$

**Bi-polar :**

$
bipolar(y_{in}) = \left\{
    \begin{array}\\
        1 , & \mbox{if } \ y_{in} > 0 \\
        y_{in} , & \mbox{if } \ y_{in} = 0 \\
        -1 , & \mbox{if } \ y_{in} < 0
    \end{array}
\right.
$

**NOTE : I will be using the bipolar activation as the output demands it.**

In [4]:
def forward_activation(z):
    z = np.array(z)
    a = np.sign(z)
    a = a + (1*(a==0))
    
    return a

def backward_activation(z):
    z = np.array(z)
    a = np.sign(z)
    a = a - (1*(a==0))
    
    return a

### Forward Checking

$ Y_{in} = bipolar(X*W) $

In [5]:
Y_in = forward_activation(np.dot(X, W))

for i in range(4):
    print("Y["+ str(i) +"]    - ", Y[i, :])
    print("Y_in["+ str(i) +"] - ", Y_in[i, :], '\n')

Y[0]    -  [1 1 1]
Y_in[0] -  [1 1 1] 

Y[1]    -  [-1 -1 -1]
Y_in[1] -  [-1 -1 -1] 

Y[2]    -  [-1  1  1]
Y_in[2] -  [-1  1  1] 

Y[3]    -  [ 1 -1  1]
Y_in[3] -  [ 1 -1  1] 



### Backward Checking

$ X_{in} = bipolar(Y*W^T) $

In [6]:
X_in = backward_activation(np.dot(Y, W.T))

for i in range(4):
    print("X["+ str(i) +"]    - ", X[i, :])
    print("X_in["+ str(i) +"] - ", X_in[i, :], '\n')

X[0]    -  [1 1 1 1 1 1]
X_in[0] -  [1 1 1 1 1 1] 

X[1]    -  [-1 -1 -1 -1 -1 -1]
X_in[1] -  [-1 -1 -1 -1 -1 -1] 

X[2]    -  [ 1 -1 -1  1  1  1]
X_in[2] -  [ 1 -1 -1  1  1  1] 

X[3]    -  [ 1  1 -1 -1 -1 -1]
X_in[3] -  [ 1  1 -1 -1 -1 -1] 



------

**As we can see the predictions and the expectations are exactly the same, implying that BAM works perfectly**